In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as kl

In [14]:
ml=[1,3,1,2,4,5,8,9,5,5,-3,4,6,7,1]

In [15]:
slk=kl.array(ml)

In [10]:
print(slk)

[1 3 1 2 4 5 8 9 5 5 3 4 6 7]


In [11]:
type(slk)

numpy.ndarray

### slk

In [13]:
kl.shape(slk)

(14,)

In [15]:
slk.reshape(7,2)

array([[1, 3],
       [1, 2],
       [4, 5],
       [8, 9],
       [5, 5],
       [3, 4],
       [6, 7]])

In [8]:
kl.absolute(slk)

array([1, 3, 1, 2, 4, 5, 8, 9, 5, 5, 3, 4, 6, 7])

In [12]:
slk=kl.array(1,3,1,2,4,5,8,9,5,5,-3,4,6,7,2)

TypeError: array() takes from 1 to 2 positional arguments but 15 were given

In [16]:
slk

array([ 1,  3,  1,  2,  4,  5,  8,  9,  5,  5, -3,  4,  6,  7,  1])

In [22]:
s=slk.reshape(5,3)

In [23]:
s[1:,1:]

array([[ 4,  5],
       [ 9,  5],
       [-3,  4],
       [ 7,  1]])

In [24]:
y=s.copy()

In [25]:
y

array([[ 1,  3,  1],
       [ 2,  4,  5],
       [ 8,  9,  5],
       [ 5, -3,  4],
       [ 6,  7,  1]])