# Use of numpy
## call it  by import ___ as___ 


In [66]:
import numpy as ty

# array fn is used to create vector
## basically here we use ty. then hit tab to find all the fn in numpy library
## shift+Tab will provide the structure of the perticularr  ffn and ddetails


# first we need to create a list


In [67]:
lis=[1,2,3,4,-5,2,2,4,5,5,3,2]

# now we create array or vector by using array fn
`

In [72]:
arr=ty.array(lis)

In [76]:
arr

array([ 1,  2,  3,  4, -5,  2,  2,  4,  5,  5,  3,  2])

In [74]:

arr==4

array([False, False, False,  True, False, False, False,  True, False,
       False, False, False])

In [75]:
arr[arr==4]

array([4, 4])

In [6]:
print(lis)

[1, 2, 3, 4, -5, 2, 2, 4, 5, 5, 3, 2]


In [7]:
print(arr)

[ 1  2  3  4 -5  2  2  4  5  5  3  2]


In [8]:
arr.any()

True

In [9]:
arr.min()

-5

In [10]:
arr.shape

(12,)

In [11]:
arr_7=arr*7


In [12]:
arr1=arr.reshape(4,3)

In [13]:
 arr1

array([[ 1,  2,  3],
       [ 4, -5,  2],
       [ 2,  4,  5],
       [ 5,  3,  2]])

In [14]:
print(arr1)

[[ 1  2  3]
 [ 4 -5  2]
 [ 2  4  5]
 [ 5  3  2]]


# indexing of two dim array is done bby describing two dim [_:_,_:_]
# first indexing describes row and second is column 
# before : is the first index of row or column and after:  is until which position we want t continue indexing

In [15]:
arr1[:,:]

array([[ 1,  2,  3],
       [ 4, -5,  2],
       [ 2,  4,  5],
       [ 5,  3,  2]])

In [16]:
arr1[0:3,2:3]

array([[3],
       [2],
       [5]])

In [17]:
arr1[0:3,:]

array([[ 1,  2,  3],
       [ 4, -5,  2],
       [ 2,  4,  5]])

# arange is the fn that used as seq on r creating arithmetic progression

In [18]:
ty.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

# linspace is the fn that create arithmatic progression 

In [19]:
ty.linspace(2,10)

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [20]:
arrr=ty.array(ty.arange(2,20,2))

In [21]:
arrr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

# copy fn

In [22]:
arrr[2:5]=500
arrr

array([  2,   4, 500, 500, 500,  12,  14,  16,  18])

In [23]:
arr1=arrr

In [24]:
arr1[2:4]=900
arr1

array([  2,   4, 900, 900, 500,  12,  14,  16,  18])

In [25]:
arrr

array([  2,   4, 900, 900, 500,  12,  14,  16,  18])

In [26]:
arr1=arrr.copy() # this create a space for the new variable but will not change the old variable

In [27]:
arr1

array([  2,   4, 900, 900, 500,  12,  14,  16,  18])

In [28]:
arr1[5:7]=400

In [29]:
arr1

array([  2,   4, 900, 900, 500, 400, 400,  16,  18])

In [30]:
arrr

array([  2,   4, 900, 900, 500,  12,  14,  16,  18])

In [31]:
arrr>3

array([False,  True,  True,  True,  True,  True,  True,  True,  True])

In [32]:
arrr[arrr>500]

array([900, 900])

In [33]:
ty.arange(2,12).reshape(5,2)

array([[ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [34]:
ty.abs(lis)

array([1, 2, 3, 4, 5, 2, 2, 4, 5, 5, 3, 2])

In [35]:
ty.append([3,3,3],[4,5,6])

array([3, 3, 3, 4, 5, 6])

In [36]:
ty.append([3,3,3],[4,5,6],axis=0)

array([3, 3, 3, 4, 5, 6])

In [54]:
ty.append([[3,3,3]],[[4,5,6]],axis=0)

array([[3, 3, 3],
       [4, 5, 6]])

In [38]:
ty.append([[3,3,3]],[[4,5,6]],axis=1)

array([[3, 3, 3, 4, 5, 6]])

In [39]:
ty.append([[3,3],[4,5]],[[5,5],[7,8]],axis=0)

array([[3, 3],
       [4, 5],
       [5, 5],
       [7, 8]])

In [40]:
ty.append([[3,3],[4,5]],[[5,5],[7,8]])

array([3, 3, 4, 5, 5, 5, 7, 8])

In [41]:
[[5,5],[7,8]]

[[5, 5], [7, 8]]

In [42]:
ty.ones(8) #default float


array([1., 1., 1., 1., 1., 1., 1., 1.])

In [43]:
ty.ones(8,dtype=int)# now integer

array([1, 1, 1, 1, 1, 1, 1, 1])

In [44]:
ty.ones((8,3,4   # 3 dims array
        )) 

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

# Data Types in NumPy
## NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

- Below is a list of all data types in NumPy and the characters used to represent them.

- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
-  O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )

In [1]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


# Creating Arrays With a Defined Data Type
## We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements:



In [2]:
# Create an array with data type string:

import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


b'2'

In [6]:
import numpy as np

arr = np.array(['a', '2', '3'], dtype='U')
arr


array(['a', '2', '3'], dtype='<U1')

# Converting Data Type on Existing Arrays
## The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

## The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

## The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [7]:
#Change data type from float to integer by using 'i' as parameter value:

import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


# The Difference Between Copy and View
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

- The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

- The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [8]:
#Make a copy, change the original array, and display both arrays:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)


[42  2  3  4  5]
[1 2 3 4 5]


In [9]:
#Make a view, change the original array, and display both arrays:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)
#The original array SHOULD be affected by the changes made to the view.

[42  2  3  4  5]
[42  2  3  4  5]


# Check if Array Owns its Data
## As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

## Every NumPy array has the attribute base that returns None if the array owns the data.

## Otherwise, the base  attribute refers to the original object.

In [156]:
#Print the value of the base attribute to check if an array owns it's data or not:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)
y.base

None
[1 2 3 4 5]


array([1, 2, 3, 4, 5])

In [11]:
#Check if the returned array is a copy or a view:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)


[1 2 3 4 5 6 7 8]


# `Unknown Dimension
## You are allowed to have one "unknown" dimension.

## Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

## Pass -1 as the value, and NumPy will calculate this number for you.

In [12]:
# Convert 1D array with 8 elements to 3D array with 2x2 elements:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)  #Note: We can not pass -1 to more than one dimension.

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [13]:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
narr=arr.reshape(2,4)


In [14]:
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
print(narr.flatten())
print(narr.flatten().base)

[1 2 3 4 5 6 7 8]
None


In [19]:
narr.ravel().base ## this is the diff between ravel and flatten

array([1, 2, 3, 4, 5, 6, 7, 8])

# Iterating Arrays
## Iterating means going through elements one by one.

## As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

# If we iterate on a 1-D array it will go through each element one by one.

In [21]:
#Iterate on the elements of the following 1-D array:

import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)


1
2
3


In [22]:
 ## Iterate on the elements of the following 2-D array:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [23]:
##terate down to the scalars:

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


# Iterating Arrays Using nditer()
## The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.

## Iterating on Each Scalar Element
## In basic for loops, iterating through each scalar of an array we need to use n for loop😦😦😦😦😦😦😦s which can be difficult to write for arrays with very high dimensionality.

In [24]:
#Iterate through the following 3-D array:

import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


# Iterating Array With Different Data Types
## We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.

## NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

In [25]:
#Iterate through the array as a string:

import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


In [29]:
import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, op_dtypes=['S']):
  print(x)

TypeError: Iterator operand required copying or buffering, but neither copying nor buffering was enabled

# Iterating With Different Step Size
 ## We can use filtering and followed by iteration.# 

In [30]:
#Iterate through every scalar element of the 2D array skipping 1 element:

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [31]:
my_list = [21, 44, 35, 11]

# where "idx" = "index"
for idx, val in enumerate(my_list):
    print(idx, val)

0 21
1 44
2 35
3 11


# Enumerated Iteration Using ndenumerate()
Enumeration means mentioning sequence number of somethings one by one.

Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

Example


In [33]:
#Enumerate on following 1D arrays elements:

import numpy as np

arr = np.array([1, 2, 3])

for ix, x in np.ndenumerate(arr):
  print(ix, x)

(0,) 1
(1,) 2
(2,) 3


In [34]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [36]:
import numpy as np

arr = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]],[[5,6,9,9],[1,3,4,6]]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 5
(0, 1, 1) 6
(0, 1, 2) 7
(0, 1, 3) 8
(1, 0, 0) 5
(1, 0, 1) 6
(1, 0, 2) 9
(1, 0, 3) 9
(1, 1, 0) 1
(1, 1, 1) 3
(1, 1, 2) 4
(1, 1, 3) 6


In [37]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [40]:
import numpy as np

arr = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]],[[5,6,9,9]]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) [[1, 2, 3, 4], [5, 6, 7, 8]]
(1,) [[5, 6, 9, 9]]


C:\Users\91894\AppData\Local\Temp\ipykernel_27888\3688837611.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]],[[5,6,9,9]]])


# Joining NumPy Arrays
## Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0

In [41]:
#Join two arrays

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [46]:
#Join two 2-D arrays along rows (axis=1):

import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1,arr2,arr2), axis=1)

print(arr)

[[1 2 5 6 5 6]
 [3 4 7 8 7 8]]


# Joining Arrays Using Stack Functions
Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.#  

In [47]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)


[[1 4]
 [2 5]
 [3 6]]


# Stacking Along Rows
NumPy provides a helper function: hstack() to stack along rows.

Example

In [51]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


# Stacking Along Columns
NumPy provides a helper function: vstack()  to stack along columns.

In [52]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)


[[1 2 3]
 [4 5 6]]


# Stacking Along Height (depth)
NumPy provides a helper function: dstack() to stack along height, which is the same as depth

In [53]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)


[[[1 4]
  [2 5]
  [3 6]]]


# Splitting NumPy Arrays
Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [55]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [54]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)


[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [56]:
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


# Splitting 2-D Arrays
Use the same syntax when splitting 2-D arrays.

Use the array_split() method, pass in the array you want to split and the number of splits you want to do.

Example


In [58]:


arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)


[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [60]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


# An alternate solution is using hsplit() opposite of hstack()

In [61]:
##Use the hsplit() method to split the 2-D array into three 2-D arrays along rows.

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


# NumPy Searching Arrays
Searching Arrays
You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

In [62]:
#Find the indexes where the value is 4:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)


(array([3, 5, 6], dtype=int64),)


In [63]:
#Find the indexes where the values are even:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


# Search Sorted
There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order
## The searchsorted() method is assumed to be used on sorted arrays. 

In [74]:
#Find the indexes where the value 7 should be inserted:

import numpy as np

arr = np.array([6,5 ,5, 10 , 10, 7,7, 8,3,2, 5 , 9])

x = np.searchsorted(arr, 7)

print(x)
#Example explained: The number 7 should be inserted on index 1 to remain the sort order.

'''The method starts the search from the left and returns the first index where the number 7 is no longer larger than the 
 next value.'''

3


'The method starts the search from the left and returns the first index where the number 7 is no longer larger than the \n next value.'

# Search From the Right Side
By default the left most index is returned, but we can give side='right' to return the right most index instead.

Example

In [75]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


## Multiple Values
To search for more than one value, use an array with the specified values.

Example
Find the indexes where the values 2, 4, and 6 should be inserted:



In [76]:
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


# Sorting Arrays
Sorting means putting elements in an ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

The NumPy ndarray object has a function called sort(), that will sort a specified array.

In [77]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))


[0 1 2 3]


In [84]:
#Sort the array alphabetically:

import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [85]:
#Sort a boolean array:

import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))


[False  True  True]


In [ ]:
# Sorting a 2-D Array
If you use the sort() method on a 2-D array, both arrays will be sorted:



In [86]:

#Sort a 2-D array:

import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


# Filtering Arrays
Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

A boolean index list is a list of booleans corresponding to indexes in the array.

If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

In [87]:
#Create an array from the elements on index 0 and 2:

import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)
#The example above will return [41, 43], why?

#Because the new array contains only the values where the filter array had the value True, in this case, index 0 and 2.

[41 43]


# Creating the Filter Array
In the example above we hard-coded the True and False values, but the common use is to create a filter array based on conditions.

Example
Create a filter array that will return only values higher than 42:


In [89]:

import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
     filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

# Creating Filter Directly From Array
The above example is quite a common task in NumPy and NumPy provides a nice way to tackle it.

We can directly substitute the array instead of the iterable variable in our condition and it will work just as we expect it to.

Example

In [ ]:
import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)


# Random array

In [45]:
ty.random.rand(7)

array([0.98134054, 0.74700074, 0.51463216, 0.03902209, 0.71230076,
       0.09375724, 0.86303832])

In [46]:
ty.random.rand(7,2)

array([[0.3657132 , 0.12984217],
       [0.97242151, 0.2974436 ],
       [0.73257856, 0.44042145],
       [0.88537538, 0.46770865],
       [0.72256415, 0.97205827],
       [0.18586077, 0.03573571],
       [0.79806725, 0.92740422]])

In [47]:
ty.random.randn(7,2)

array([[-0.34094033,  0.17186712],
       [-0.77953674, -0.10559295],
       [-0.86267527,  0.00488151],
       [ 1.00374758, -0.71997471],
       [-0.39313721,  0.93574713],
       [-0.05752119,  0.39425755],
       [ 0.36771968, -1.11850556]])

In [48]:
ty.random.randint(7,100,9)

array([39, 16, 59, 68, 83, 16, 51, 35, 56])

In [49]:
ty.random.beta(1,2,10)

array([0.19466071, 0.2975353 , 0.95577091, 0.80105213, 0.05938794,
       0.06644022, 0.18354793, 0.10132718, 0.44294239, 0.3682778 ])

In [50]:
ty .random.gamma(1,4,10)

array([ 3.49765128,  2.47070369,  2.4702339 ,  0.32866926,  5.93685684,
        0.85390661,  1.20674558,  7.1925241 ,  7.49239955, 10.01249561])

In [51]:
ty .random.f(2,2,10)

array([0.90320161, 0.36849831, 0.17218533, 0.30773252, 0.69541537,
       0.83928438, 0.77603062, 3.27399273, 0.48358291, 0.53266391])

In [52]:
ty .random.binomial(3,0.3,10)

array([1, 1, 1, 1, 1, 0, 0, 1, 1, 1])

In [53]:
ty.random.standard_cauchy(10)

array([-82.76967285,   1.20867899,   2.6308552 ,   0.5951615 ,
         4.64001515,  -0.52272916,  -4.83449836,   1.84139424,
        -0.59068164,  -0.37112119])

array(['c'], dtype='<U1')

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U1'), dtype('int32')) -> None

# What are ufuncs?
ufuncs stands for "Universal Functions" and they are NumPy functions that operate on the ndarray object.

# Why use ufuncs?
- ufuncs are used to implement vectorization in NumPy which is way faster than iterating over elements.

- They also provide broadcasting and additional methods like reduce, accumulate etc. that are very helpful for computation.

- ufuncs also take additional arguments, like:

 - where: boolean array or condition defining where the operations should take place.

 - dtype: defining the return type of elements.

 - out :output array where the return value should be copied.

# What is Vectorization?
Converting iterative statements into a vector based operation is called vectorization.

It is faster as modern CPUs are optimized for such operations.

Add the Elements of Two Lists
list 1: [1, 2, 3, 4]

list 2: [4, 5, 6, 7]

One way of doing it is to iterate over both of the lists and then sum each elements.



In [90]:
#Without ufunc, we can use Python's built-in zip() method:

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
  z.append(i + j)
print(z)


[5, 7, 9, 11]


In [ ]:
# NumPy has a ufunc for this, called add(x, y) that will produce the same result.

In [91]:
#With ufunc, we can use the add() function:

import numpy as np

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)

[ 5  7  9 11]


# How To Create Your Own ufunc
To create your own ufunc, you have to define a function, like you do with normal functions in Python, then you add it to your NumPy ufunc library with the frompyfunc() method.

The frompyfunc() method takes the following arguments:

- function - the name of the function.
- inputs - the number of input arguments (arrays).
- outputs - the number of output arrays.


In [104]:
import numpy as np

def myadd(x, y):
  return x+y
  
 

myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

[6 8 10 12]


# Check if a Function is a ufunc
Check the type of a function to check if it is a ufunc or not.

A ufunc should return <class 'numpy.ufunc'>.



In [105]:

#Check if a function is a ufunc:

import numpy as np

print(type(np.add))

<class 'numpy.ufunc'>


In [106]:
import numpy as np

print(type(np.concatenate))

<class 'function'>


In [107]:
import numpy as np

if type(np.add) == np.ufunc:
  print('add is ufunc')
else:
  print('add is not ufunc')

add is ufunc


In [108]:
import numpy as np

arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)

print(newarr)


[30 32 34 36 38 40]


In [109]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)

print(newarr)


[-10  -1   8  17  26  35]


In [114]:
"h"+"7"


'h7'

# Array Arithmatic

In [115]:


import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.multiply(arr1, arr2)

print(newarr)


[ 200  420  660  920 1200 1500]


In [116]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

newarr = np.divide(arr1, arr2)

print(newarr)


[ 3.33333333  4.          3.          5.         25.          1.81818182]


In [121]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6 , 8, 2, 3])

newarr = np.power(arr1, arr2)

print(newarr)

[      1000    3200000  729000000 -520093696       2500     216000]


In [122]:
#Remainder
#Both the mod() and the remainder() functions return the remainder of the values in the first array corresponding to the values in the second array, and return the results in a new array.



import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)

print(newarr)

[ 1  6  3  0  0 27]


In [123]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.remainder(arr1, arr2)

print(newarr)

[ 1  6  3  0  0 27]


In [124]:
#The divmod() function return both the quotient and the the mod. The return value is two arrays, the first array contains
#the quotient and second array contains the mod.

import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.divmod(arr1, arr2)

print(newarr)

(array([ 3,  2,  3,  5, 25,  1], dtype=int32), array([ 1,  6,  3,  0,  0, 27], dtype=int32))


In [125]:
import numpy as np

arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)

print(newarr)

[1 2 1 2 3 4]


## Truncation
Remove the decimals, and return the float number closest to zero. Use the trunc() and fix() function


In [127]:
#Truncate elements of following array:

import numpy as np

arr = np.trunc([-3.1666, 3.6667])

print(arr)

[-3.  3.]


In [128]:
#Same example, using fix():

import numpy as np

arr = np.fix([-3.1666, 3.6667])

print(arr)

[-3.  3.]


In [129]:
#Round off 3.1666 to 2 decimal places:

import numpy as np

arr = np.around(3.1666, 2)

print(arr)

3.17


In [130]:
#Floor the elements of following array:

import numpy as np

arr = np.floor([-3.1666, 3.6667])

print(arr)

[-4.  3.]


In [131]:
#Ceil the elements of following array:

import numpy as np

arr = np.ceil([-3.1666, 3.6667])

print(arr)

[-3.  4.]


## Natural Log, or Log at Base e
Use the log() function to perform log at the base e.

Example


In [132]:
#Find log at base e of all elements of following array:

import numpy as np

arr = np.arange(1, 10)

print(np.log(arr))


[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


## Log at Any Base
NumPy does not provide any function to take log at any base, so we can use the frompyfunc() function along with inbuilt function math.log() with two input parameters and one output parameter


In [133]:
from math import log
import numpy as np

nplog = np.frompyfunc(log, 2, 1)

print(nplog(100, 15))

1.7005483074552052


In [134]:
15**1.7005483074552052

100.00000000000001

# What is the difference between summation and addition?

Addition is done between two arguments whereas summation happens over n elements.

In [135]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.add(arr1, arr2)

print(newarr)


[2 4 6]


In [136]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2])

print(newarr)

12


In [137]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2], axis=1)

print(newarr)

[6 6]


# Cummulative Sum


In [138]:
import numpy as np

arr = np.array([1, 2, 3])

newarr = np.cumsum(arr)

print(newarr)


[1 3 6]


# product

In [139]:
#Find the product of the elements of this array:

import numpy as np

arr = np.array([1, 2, 3, 4])

x = np.prod(arr)

print(x)

24


In [140]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

x = np.prod([arr1, arr2])

print(x)

40320


In [141]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

newarr = np.prod([arr1, arr2], axis=1)

print(newarr)

[  24 1680]


In [142]:
import numpy as np

arr = np.array([5, 6, 7, 8])

newarr = np.cumprod(arr)

print(newarr)


[   5   30  210 1680]


In [143]:
import numpy as np

arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr)

print(newarr)

[  5  10 -20]


In [144]:
import numpy as np

x = np.arcsin(1.0)

print(x)

1.5707963267948966


# Create Sets in NumPy
We can use NumPy's unique() method to find unique elements from any array. E.g. create a set array, but remember that the set arrays should only be 1-D arrays.

In [146]:
#convert following array with repeated elements to a set:

import numpy as np

arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

x = np.unique(arr)

print(x)

[1 2 3 4 5 6 7]


In [147]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.union1d(arr1, arr2)

print(newarr)

[1 2 3 4 5 6]


In [152]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.intersect1d(arr1, arr2, assume_unique=True)

print(newarr)
'''Note: the intersect1d() method takes an optional argument assume_unique, which if set to True can speed up computation. 
    It should always be set to True when dealing with sets.'''

[3 4]


'Note: the intersect1d() method takes an optional argument assume_unique, which if set to True can speed up computation. \n    It should always be set to True when dealing with sets.'

In [151]:
import numpy as np

set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setdiff1d(set1, set2, assume_unique=True)

print(newarr)


[1 2]


In [153]:
import numpy as np

set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setxor1d(set1, set2, assume_unique=True)

print(newarr)

[1 2 5 6]
